Update for 3.x.  Packages now work and deploy correctly on both sysvinit and systemd systems, along with updated version of ffmpeg.  Now requires Java 8, per OC 3.0 requirements.

diff --git a/opencast/debian/opencast-common.postinst b/opencast/debian/opencast-common.postinst
--- a/opencast/debian/opencast-common.postinst
+++ b/opencast/debian/opencast-common.postinst
@@ -17,56 +17,56 @@ OC_USER=opencast
 OC_UID=7967
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
-#          <conflicting-package> <version>
+#    * <postinst> `configure' <most-recently-configured-version>
+#    * <old-postinst> `abort-upgrade' <new version>
+#    * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#      <new-version>
+#    * <postinst> `abort-remove'
+#    * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#      <failed-install-package> <version> `removing'
+#      <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 create_group() {
-    if ! getent group $OC_GROUP > /dev/null 2>&1; then
-        addgroup --gid $OC_GID $OC_GROUP
-    fi
+  if ! getent group $OC_GROUP > /dev/null 2>&1; then
+    addgroup --gid $OC_GID $OC_GROUP
+  fi
 }
 
 create_user() {
-    if ! getent passwd $OC_USER > /dev/null 2>&1; then
-        adduser --no-create-home --uid $OC_UID --ingroup $OC_GROUP \
-                --home $OC_HOME --shell /usr/sbin/nologin $OC_USER
-    fi
+  if ! getent passwd $OC_USER > /dev/null 2>&1; then
+    adduser --no-create-home --uid $OC_UID --ingroup $OC_GROUP \
+        --home $OC_HOME --shell /usr/sbin/nologin $OC_USER
+  fi
 }
 
 apply_permissions() {
-	if ! dpkg-statoverride --list $1 >/dev/null 2>&1; then
-		dpkg-statoverride --update --add $OC_USER $OC_GROUP 755 $1
-		chown -R $OC_USER:$OC_GROUP $1
-	fi
+  if ! dpkg-statoverride --list $1 >/dev/null 2>&1; then
+    dpkg-statoverride --update --add $OC_USER $OC_GROUP 755 $1
+    chown -R $OC_USER:$OC_GROUP $1
+  fi
 }
 
 case "$1" in
-    configure)
-        create_group
-        create_user
+  configure)
+    create_group
+    create_user
 
-	apply_permissions $OC_HOME
-	apply_permissions $OC_CONFIG
-	apply_permissions $OC_LOG
-	apply_permissions $OC_DATA
-	apply_permissions $OC_KARAF_DATA
-    ;;
+    apply_permissions $OC_HOME
+    apply_permissions $OC_CONFIG
+    apply_permissions $OC_LOG
+    apply_permissions $OC_DATA
+    apply_permissions $OC_KARAF_DATA
+  ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
+  abort-upgrade|abort-remove|abort-deconfigure)
+  ;;
 
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
+  ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
